- .github/workflows/ci.yml
- .github/workflows/pypi-publish.yml
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- setup.py
- tox.ini
Update CI workflow to use latest ubuntu and python v3.12
close #024
> FC-0057: Update CI workflow

- .github/workflows/mypy.yml
- forum/models/base_model.py
- forum/models/contents.py
- forum/models/threads.py
- forum/models/users.py
- forum/mongo.py
- forum/settings/common.py
- forum/settings/production.py
- forum/utils.py
- forum/views/proxy.py
- mypy.ini
- requirements/base.txt
- requirements/ci.in
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.in
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- tests/test_models/test_users.py
- make a separate workflow for mypy typing checks
- add mypy into requirements
- close #27
> FC-0057: implement mypy in forum codebase

- tests/test_views/test_pins.py
> tests: add unit test for the /pins API

- forum/models/model_utils.py
- forum/urls.py
- forum/views/comments.py
- tests/test_views/test_comments.py
- implement thread create comment API, it will create a parent comment on a thread
- refactored code to minimize the duplications
- add its test
close #59
> feat: implement thread create comment API

- forum/views/votes.py
- tests/test_views/test_votes.py
Implement test cases for upvote and downvote comments and threads
close #26
> FC-0057: Add vote tests

- forum/models/model_utils.py
- forum/models/users.py
- forum/views/flags.py
- tests/test_views/test_flags.py
This PR adds update_stats_for_course method in flags api. 
close #030
> feat: update flags apis to include course_stats updates

- forum/utils.py
- It will log an error whenever proxy API is called, that redirect calls to v1.
> feat: add error log if calls proxy API

- forum/handlers.py
- forum/models/comments.py
- forum/models/model_utils.py
- forum/models/threads.py
- forum/views/comments.py
- forum/views/search.py
- forum/views/subscriptions.py
- tests/test_models/test_comments.py
- tests/test_models/test_threads.py
- tests/test_views/test_comments.py
- tests/test_views/test_flags.py
- tests/test_views/test_search.py
- tests/test_views/test_threads.py
- tests/test_views/test_users.py
- tests/test_views/test_votes.py
The pull request contains tests to maximize the test coverage.
- We have increased the coverage from 84 to 87, and we plan to improve it further in future PRs.
- The test coverage should be expanded for utilities and elastic search classes. To keep track of this, we have created issue #96.
close #46
> fix: add tests to maximize the test coverage

- docs/decisions/0002-forum_v1_migration_to_v2.rst
Document the differences in the v1 and v2 elastic search documents.
close #91
> docs: document differences in v1 and v2 indexes of the elasticsearch

- forum/backends/mysql/models.py
- this commit fix this issue 
https://github.com/openedx/edx-platform/actions/runs/11254779718/job/31292928835?pr=35490
> fix: add app label for ForumUser model

- forum/backends/mysql/models.py
Add app_label for MongoContent model that fix static CI tests in edx-platform.
> fix: add missing app_label

- forum/api/search.py
- forum/backends/mongodb/api.py
- forum/backends/mysql/__init__.py
- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
- forum/handlers.py
- forum/search/backend.py
- forum/search/es.py
- forum/search/mappings.py
- tests/test_views/test_search.py
- tests/test_views/test_votes.py
The PR contains updates to the search functionality to work with MySQL and Mongo.
close #106
> feat: update search to work with mysql and mongo

- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
The PR contains fixes for the type in Comment and CommentThread models.
> fix: entity type for Comment and CommentThread models

- tests/test_backends/test_mysql/test_api.py
Add unit tests for mysql api for user course stats close #122
> feat: Bump user stats mysql api coverage

- .github/workflows/pypi-publish.yml
- README.rst
- setup.py
This will make it possible to push the package to pypi on release.
> fix: rename python package to openedx-forum

- forum/__init__.py
- forum/management/commands/delete_unused_forum_indices.py
- forum/management/commands/initialize_forum_indices.py
- forum/management/commands/rebuild_forum_indices.py
- forum/management/commands/validate_forum_indices.py
- forum/search/meilisearch.py
- setup.py
The management/ directory was missing from the package created with `python setup
sdist` because __init__.py files were not included in these directories.
> fix: pypi package generation

- README.rst
Forum is now widely available in Sumac.
> docs: remove outdated integration warning

- forum/backends/mongodb/contents.py
- forum/management/commands/forum_create_mongodb_indexes.py
**Description:**
Added a management command to build MongoDB indexes
> Add management command for creating mongodb indexces

- README.rst
**Description**
Added usage of the following management commands in ReadMe.
- Creating MongoDB indexes
- Initialize search indices
- Rebuild search indices
> docs: mention usage of management commands

- forum/api/threads.py
- forum/backends/mongodb/api.py
- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
- forum/serializers/thread.py
- tests/test_views/test_threads.py
The PR contains a fix for the issue mentioned in the PR #142
> fix: add group_id and group_ids params in the get_user_threads

- forum/backends/backend.py
- forum/backends/mongodb/api.py
- forum/backends/mongodb/contents.py
- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
- forum/serializers/thread.py
- tests/test_views/test_threads.py
The PR fixes the pagination issue in a thread comments.
close #151
> fix: pagination for comments API

- .github/workflows/pypi-publish.yml
- .readthedocs.yaml
This PR includes the following updates:
Ubuntu Version: Updated the Ubuntu version in the PyPI publish workflow to the latest stable release to ensure compatibility with the latest packages and dependencies.
ReadTheDocs Configuration: Edited the .readthedocs.yaml file to align with recent project requirements or to fix any issues with documentation builds.
> chore: update ubuntu image to latest in forum workflows

- forum/__init__.py
This PR bumps up the version to 0.1.9
> chore: bump forum version to 0.1.9

- catalog-info.yaml
This PR updates catalog-info.yaml with relevant values.
close https://github.com/openedx/forum/issues/161
> chore: Update catalog-info with details

- forum/__init__.py
- forum/api/comments.py
- forum/api/threads.py
- forum/api/users.py
This PR includes minor fixes identified during the removal of legacy code from the edx-platform. It addresses the following:
- Removes duplicate entries in the update functions for threads and comments.
- Makes group_ids an optional field in the get_user method.
- Bumps the package version to 0.3.1.
> Depr legacy forum

- forum/api/pins.py
- forum/backends/mysql/api.py
- tests/conftest.py
- tests/test_views/test_pins.py
- tests/test_views/test_threads.py
- tests/test_views/test_threads_v2.py
Eliminate the Mongo code for the Pins APIs.
> feat: remove pins mongo code

- forum/api/flags.py
- tests/e2e/test_users.py
- tests/e2e/test_users_v2.py
- tests/test_views/test_flags.py
- tests/test_views/test_threads.py
- tests/test_views/test_threads_v2.py
Eliminate the Mongo code for the Flags APIs.
> feat: remove flags mongo code

- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
This PR uses serializer instead of directly calling model apis in votes view
> feat: refactor votes api view

- forum/api/commentables.py
- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
- forum/serializers/commentables.py
This PR uses serializer instead of directly calling model apis in commentables view
> feat: Refactor Commentables api view

- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
This PR refactors flags api methods so that orm logic stays within the models.
> feat: refactor flags api

- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
This PR updates subscriptions api views methods to have the mysql/orm code to respective models and trim the api methods.
> feat: Refactor subscriptions api view

- forum/api/users.py
- forum/backends/backend.py
- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
- forum/serializers/thread.py
- tests/e2e/test_users.py
- tests/e2e/test_users_v2.py
This PR moves the ORM logic from MySQL api to model methods in favor of a cleaner code.
> feat: Refactor Users api view

- forum/api/comments.py
- forum/backends/backend.py
- forum/backends/mysql/api.py
- forum/backends/mysql/models.py
- forum/views/comments.py
This PR refactors mysqlbackend class methods to shift orm logic to models for comments views.
> feat: Refactor Comments api view

- .github/workflows/ci.yml
- CHANGELOG.rst
- forum/__init__.py
- requirements/doc.in
- requirements/doc.txt
- requirements/test.in
- requirements/test.txt
- tox.ini
1. Check that the CI is failing for the first commit and passing for the second one.
> build: add Python package validation and fix CHANGELOG formatting

- forum/api/search.py
- forum/api/users.py
- forum/backends/backend.py
- forum/backends/mongodb/api.py
- forum/backends/mysql/api.py
This PR fixes the issue where data in the topic tab wasn't being fetched based on user role.
close: https://github.com/openedx/forum/issues/218
> fix: Topic tab not returning data based on roles
