.github/workflows/ci.yml, forum.egg-info/entry_points.txt, forum/apps.py, forum/settings/common.py, forum/settings/production.py, forum/urls.py, forum/views.py, pylintrc, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt, setup.py, test_settings.py, tox.ini
- Add apps.py and entry points for the app to be detected by LMS
- create a thin proxy API, this is the API we'll be editing to first call the cs_comments_service urls then calling its own endpoints
close #2 
=> FC-0057: add a thin proxy API btw LMS and v1

forum/utils.py, forum/views.py
- add missing params parameter to the requests call
- simplify all requests call into a single request helper
=> FC-0057: add params parameter to the requests

README.md, README.rst
Updated README with installation steps, development guide, and project motivation.
close https://github.com/edly-io/forum/pull/3
=> FC-0057: Updated README with the installation guide

.gitignore, forum/models/__init__.py, forum/models/comments.py, forum/models/contents.py, forum/models/model_utils.py, forum/models/threads.py, forum/serializers/comment.py, forum/serializers/contents.py, forum/serializers/thread.py, forum/serializers/votes.py, forum/settings/common.py, forum/settings/production.py, forum/urls.py, forum/views/flags.py, forum/views/votes.py, tests/conftest.py, tests/test_models/conftest.py, tests/test_models/test_comments.py, tests/test_models/test_threads.py, tests/test_models/test_users.py, tests/test_views/__init__.py, tests/test_views/test_flags.py
Updates:
- Added upvote & downvote APIs
- Added comment model and tests
close https://github.com/edly-io/forum/issues/16
=> FC-0057: Add Vote APIs and Comment Model

forum/models/base_model.py, forum/models/contents.py, forum/models/users.py, forum/mongo.py, tests/conftest.py, tests/test_models/test_comments.py, tests/test_models/test_threads.py, tests/test_models/test_users.py, tests/test_views/test_flags.py
We split the ModelBackend in database/collection. This means that we can override the database globally in unit tests. This also drastically simplifies model constructors.
=> chore: greatly simplify mocking and models API

docs/conf.py, forum/models/base_model.py, forum/models/comments.py, forum/models/contents.py, forum/models/threads.py, forum/models/users.py, forum/serializers/contents.py, forum/serializers/votes.py, forum/settings/common.py, forum/settings/production.py, test_utils/client.py, tests/conftest.py, tests/test_views/test_flags.py
1. Child model classes inherited the insert and update methods, but with a different signature. This violated the Liskov principle, which is explained here: https://stackoverflow.com/a/54359797/356528 To bypass this, we migrated most of the Content class to a separate base class, and insert/update methods are no longer inherited.
2. We removed type ignores in serializers, which were simply missing a generic type definition.
3. We also updated the APIClient, but we failed to properly type it, because we don't know how to use "_MonkeyPatchedWSGIResponse".
=> chore: get rid of type/pylint ignore statements

forum/models/comments.py, forum/models/threads.py, forum/views/flags.py, tests/test_views/test_flags.py
This PR updates flags api to use comment and commentthread models which weren't initially present. Moreover, the api now serializes data with respective models. Unit tests updated for flags apis.
close# 044
=> chore: Refactor flags api to use comment and comment thread models

forum/index_manager.py, forum/models/base_model.py, forum/models/comments.py, forum/models/contents.py, forum/models/model_utils.py, forum/models/threads.py, forum/models/users.py, forum/serializers/contents.py, forum/serializers/custom_datetime.py, forum/serializers/thread.py, forum/settings/common.py, forum/settings/production.py, forum/urls.py, forum/utils.py, forum/views/search.py, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt
**Description**
Added the thread search API.
Close https://github.com/edly-io/forum/issues/40.
=> feat: add thread serach API

forum/mongo.py, forum/settings/common.py, forum/settings/production.py, test_settings.py
Rename mongodb host and port settings to add prefix  to avoid ambiguity with openedx close# 045
=> refactor: rename mongodb config variables

forum/management/commands/delete_unused_forum_indices.py, forum/management/commands/initialize_forum_indices.py, forum/management/commands/rebuild_forum_indices.py, forum/management/commands/validate_forum_indices.py, forum/models/base_model.py, forum/models/comments.py, forum/models/contents.py, forum/models/threads.py, forum/search/es_helper.py, forum/search/search_manager.py, forum/utils.py, forum/views/search.py, tests/test_views/test_pins.py
Commands:
- delete_unused_forum_indices: For deleting unused indices.
- initialize_forum_indices: For initializing indices.
- rebuild_forum_indices: For rebuilding indices.
- validate_forum_indices: FOr validating indices, mappings.
close https://github.com/edly-io/forum/issues/57
=> feat: add elastic search commands

forum/search/es_helper.py, forum/serializers/comment.py, forum/serializers/contents.py, forum/serializers/thread.py, forum/views/comments.py, forum/views/flags.py, forum/views/pins.py, forum/views/search.py, forum/views/subscriptions.py, forum/views/votes.py
In this PR:
- refactored serializers, now there's only one serializer for comment and thread and both inherits a single content serializer.
- Also tried overriding is_valid() method of serializer but mypy and pylint were conflicting together.
- rename serializers
=> chore: refactor serializers

forum/models/comments.py, forum/models/contents.py, forum/models/model_utils.py, forum/serializers/thread.py, forum/views/comments.py, forum/views/subscriptions.py
- `comment_count` is calculated on run time during API call in a `ThreadSerializer` and returned in a response. As a result, it does not sync with mongodb data. So it should be updated through a signal or in current implementation of mongo models, `comment_count` should be adjusted when there's any comment created/deleted. This commit will fix this issue and will update comment_count when comment is created/deleted.
- fix an issue in user subscriptions get request params validation.
- fix an issue in field name comment_count in the `ThreadSerializer`.
- code refactoring
- exclude endorsement field in case of get comment data and only save parent_id for child comment. This will keep the responses same for v1 and v2.
=> fix: issues in comment_count & subscriptions api

forum/models/model_utils.py, forum/urls.py, forum/views/commentables.py, tests/test_views/test_commentables.py
- implement commentables count API
- fix invalid parameter 'commentable_ids' error for threads API 
- implement tests for commentables count API
- close #74
This PR doesn't include below APIs as below APIs weren't being called from the frontend.
```
/:commentable_id/threads DELETE
/:commentable_id/threads GET
/:commentable_id/threads POST
```
=> FC-0057: implement commentables count API

docs/decisions/0002-forum_v1_migration_to_v2.rst, docs/references/index.rst, docs/references/v1_models.rst, forum/views/search.py
- add documentation for the forum v1 models and it's real-time data that is being saved in the collections.
- add the decisions document for the stuff that we are deprecating in forum v2.
- fix docstring for the for the SearchThreadsView API
- close #48.
=> FC-0057: document forum v1 models

forum/models/contents.py, forum/models/model_utils.py, forum/serializers/contents.py, forum/views/flags.py, tests/test_views/test_flags.py
This pr fixes flags api to update historical abuse flaggers when unflag api is called with  param set to true. Also, add historical_abuse_flaggers field in Contents serializer.
=> fix: flags api not updating historical abuse flaggers

forum/models/model_utils.py, forum/serializers/comment.py, forum/serializers/thread.py, forum/utils.py, forum/views/threads.py, tests/test_views/test_flags.py, tests/test_views/test_threads.py
- fix the response of get thread API according to query params when thread type is question
- fix the response of get thread API when answered question is marked back as not answered when thread type is question.
- fix the response of user's subscribed thread API as it wasn't deleting the subscriptions of the thread when thread was deleted, and was returning more subscribed threads in the response
- add tests for the above cases
- close #47
=> fix: differences in forum v1 and v2 get responses

forum/utils.py, forum/views/threads.py
- remove Any(collection) from str_to_bool function's argument type definition.
=> chore: remove Any(collection) from str_to_bool function

forum/api/threads.py
Add context field in the create_thread
=> fix: add context in the create_thread

README.rst, forum/backend.py, forum/management/commands/forum_delete_course_from_mongodb.py, forum/management/commands/forum_migrate_course_from_mongodb_to_mysql.py, forum/migration_helpers.py, forum/toggles.py, tests/conftest.py, tests/e2e/conftest.py, tests/test_management/test_commands/test_migration_commands.py, tests/test_views/test_commentables.py, tests/test_views/test_comments.py, tests/test_views/test_flags.py, tests/test_views/test_pins.py, tests/test_views/test_subscriptions.py, tests/test_views/test_threads.py, tests/test_views/test_users.py, tests/test_views/test_votes.py
feat: add migration command for mongo to mysql
- add migration command that copies courses data from mongodb to mysql models.
- add deletion command that deletes courses data from mongodb.
- add CourseWaffleFlag to retrieve correct backend for a course.
- enable waffle flag for course after migration is completed.
- fix patch_get_backend for `test_views/` tests.
- add unit tests for migration commands
- close #051
=> feat: add migration command for mongo to mysql

forum/backend.py, forum/backends/mongodb/api.py
- bypass searching course_id by thread/comment in mongo and then search it in mysql
- convert course_id(str) into CourseKey before passing it to CourseWaffleFlag's is_enabled method as it expects CourseKey
=> fix: issues related to course_id

forum/backends/mongodb/api.py
- We were not able to get child comments as mongo was expecing parent_id as ObjectId to get list of child comments associated with the respective parent_id(ObjectId).
=> fix: convert parent_id to ObjectId

forum/api/threads.py, forum/api/votes.py, forum/migration_helpers.py, tests/test_management/test_commands/test_migration_commands.py
fix: This PR fixes get threads apis and thread votes api as migration command weren't storing last_activity_at and commentable_id
=> fix: threads apis for mysql backend

forum/api/subscriptions.py
This PR fixes subscriptions api as course_id was not being passed hence defaulting to mongo backend
=> fix: subscriptions api

forum/backends/backend.py, forum/backends/mongodb/api.py, forum/backends/mysql/api.py, forum/backends/mysql/models.py, tests/e2e/conftest.py, tests/e2e/test_search.py, tests/e2e/test_users.py
The PR allows e2e tests to support both MySQL and Mongo.
close #117
=> feat: update e2e tests to work with both mysql and mongo

README.rst
Course waffle flag name was updated in the latest edx-platform PR: https://github.com/openedx/edx-platform/pull/35671
=> docs: fix forum v2 waffle name

forum/__init__.py, forum/search/base.py, forum/search/es.py, forum/search/meilisearch.py, test_utils/mock_es_backend.py, tests/test_meilisearch.py
In production, we sometimes observe the following error on document
deletion:
lms-1  |   File "/openedx/venv/lib/python3.11/site-packages/forum/handlers.py", line 115, in handle_deletion
lms-1  |     search_backend.delete_document(sender.index_name, document_id)
lms-1  |   File "/openedx/venv/lib/python3.11/site-packages/forum/search/meilisearch.py", line 93, in delete_document
lms-1  |     doc_pk = m.id2pk(doc_id)
lms-1  |              ^^^^^^^^^^^^^^^
lms-1  |   File "/openedx/venv/lib/python3.11/site-packages/search/meilisearch.py", line 362, in id2pk
lms-1  |     return hashlib.sha1(value.encode()).hexdigest()
lms-1  |                         ^^^^^^^^^^^^
lms-1  | AttributeError: 'int' object has no attribute 'encode'
This is due to the fact that the doc_id passed to the …
=> fix: document deletion

forum/backends/mongodb/threads.py, forum/backends/mongodb/users.py, tests/conftest.py, tests/test_views/test_threads.py
- Management command throws an error for deleted threads whose read_states still exists in the Users collection. Although it's a replica of V1(cs_comment_service) which was also keeping the read_states of deleted threads. This commit will delete the read_states of the thread from User Collection on thread deletion as keeping the read_states are of no use.
=> fix: delete read_states of thread on its deletion

forum/__init__.py, forum/settings/common.py
The forum app should not automatically override upstream settings. If it does, then it will have edx-platform point to the new forum v2 app even if the forum v2 waffle flag is toggled off.
This was causing issues for platforms running forum v1:
Traceback (most recent call last):
File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/urllib3/connection.py", line 507, in getresponse
httplib_response = super().getresponse()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/http/client.py", line 1395, in getresponse
response.begin()
File "/usr/lib/python3.11/http/client.py", line 325, in begin
version, status, reason = …
=> fix: don't override forum url if already defined

forum/__init__.py, forum/migration_helpers.py, tests/test_management/test_commands/test_migration_commands.py
Bugs:
- No.1: run migration command to migrate data from mongo to mysql, it doesn't migrate sk(sorting_key) and depth of the sub/child comments. Due to which sub-comments although being created in mysql doesn't appear on the frontend. So to reproduce this bug, simply migrate a course which has a thread with child comments at depth 1
.i.e thread -> comment on the thread -> comment on the parent comment. Now, migrate this course to mysql. Sub comments(comment on the parent comment) will not appear on frontend. One can also view the Comment in Comment model in django admin panel, sk and depth will not be there.
- No.2: create a thread in mongodb, and migrate the course with this thread to mysql. Now create a comment on this thread in mongo db. Creating a comment on thread will update it's …
=> fix: forum bug fixes related to data migration

README.rst
Turns out that forum v2 needs to be configured even if v2 is not toggled. That's because the thread ID/comment ID need to be converted to course ID to determine the course waffle flag value.
=> docs: adjust instructions for compatibility with v1

forum/__init__.py, forum/migration_helpers.py, tests/test_management/test_commands/test_migration_commands.py
In cs_comment_service, the read_state of a thread is retained even after the thread is deleted This error is occurring during migration of read_states for old courses that has data in mongodb and has read_state saved for deleted threads.
This commit ensures that the migration process will skip any read_state associated with threads that no longer exist.
close #143
=> fix: skip migrating read_state of deleted threads

forum/backends/mongodb/api.py, tests/test_views/test_threads.py
This PR fixes the get_read_states method that was only extracting the 1st course read state for users and not working for all other courses.
close #144
=> fix: get_read_states returning wrong value of read states

forum/api/threads.py
The get_user_threads api was not accepting additional arguments and there the discussion xblock wasn't working with the forum service. 
This PR adds args and kwargs params to the api to avoid breakage.
close #149
=> fix: get_user_threads api args

forum/serializers/contents.py
**Description:** This PR allows username in content serializer to be null to avoid breakages with the inline discussion module in openedx.
=> fix: inline discussion compatibility issues

forum/api/subscriptions.py, forum/utils.py, forum/views/subscriptions.py
The PR refactors the get_user_subscriptions function to use positional and optional arguments instead of a general query_params dictionary. This refactoring makes this function work similarly to other functions, such as get_user_threads.
=> fix: refactor get_user_subscriptions to unpack query_params

forum/backends/mongodb/api.py, forum/backends/mongodb/threads.py, forum/backends/mysql/api.py
This PR fixes both backends to not modify last_activity_at when pinning/unpinning threads
close: #223
=> fix: Sort threads issue after pin/unpin
